### ISSUE TITLE
It doesn‘t work

### ISSUE THREAD

**Issue by Mime-AL** [Sofronio/YouTubeTimeLineGenerator#1]
I drop the VTT file into the window.And click the"Convert to ASS".the program just clear up the text box,but nothing happen.
OS:Windows 8.1 X64

**Comment by Mime-AL** [comment]
Load Words works well

**Comment by Sofronio** [comment]
Show me the raw vtt file.

**Comment by Mime-AL** [comment]
https://1drv.ms/u/s!AglafQRlEFSchLMq18BOWbzmgLAvyg

**Comment by Sofronio** [comment]
it works on my pc, don't know why. what's your operation steps?

1. drag and drop on the top left textbox;
2. click "Process VTT"
3. click "Load Words"

it should appear.

and be sure to use the latest version, which is 0.0.3 by now.

![test](https://user-images.githubusercontent.com/11464550/39669768-ff001114-5127-11e8-9d90-91fb52cc6747.png)

**Comment by Mime-AL** [comment]
Right，I am using the latest version properly.But it wouldn't work.
![image](https://user-images.githubusercontent.com/20331044/39669962-1cef4d30-512c-11e8-8031-0eb7b9e8cf4b.png)

**Comment by Sofronio** [comment]
It is working properly, you should click the words in the text box underneath then click the third button

**Comment by Sofronio** [comment]
![qq 20180507131957](https://user-images.githubusercontent.com/11464550/39686081-892af3a0-51f9-11e8-9b8c-150873d8c3d0.png)
