### ISSUE TITLE
Application no longer working correctly

### ISSUE THREAD

**Issue by TDL3** [Sofronio/YouTubeTimeLineGenerator#3]
I have re-installed my system yesterday, and I'm running Windows 10 buid 1803 now, the problem is that  the app no longer working correctly, it does start, it will display OK when I click Process VTT, but nothing happens when I clicked the Load Words button.
I've tried everything I can think of but failed to get it to work, considering it was working smoothly before I'm thinking there might be some issues in codes due to recent updates.
p.s. I did install the required .NET Framwork

**Comment by TDL3** [comment]
This was the file I tried to ues:
[Cranking a Car with Super Capacitors (Supercap)-tKki89sq0XY.en.zip](https://github.com/Sofronio/YouTubeTimeLineGenerator/files/2195270/Cranking.a.Car.with.Super.Capacitors.Supercap.-tKki89sq0XY.en.zip)
URL of the video: https://www.youtube.com/watch?v=tKki89sq0XY

**Comment by Sofronio** [comment]
Your vtt file is already a complete cc.
It doesn't contain any word-time-info, only the time a sentence stats and ends.
You don't need to use this tool to process that.
Just use any subtitle software like Subtitle Edit to open it, and save it as srt/ass file.
That's it.

**Comment by TDL3** [comment]
Thanks a lot ^_^
