### ISSUE TITLE
在新版本VTT下 分行工具会概率吞掉一个字的最后一个词

### ISSUE THREAD

**Issue by OpaqueArc** [Sofronio/YouTubeTimeLineGenerator#5]
示例
VTT原始数据：
`
00:02:02.719 --> 00:02:05.190 align:start position:0%
competitive machine
thanks<00:02:03.040><c> to</c><00:02:03.280><c> a</c><00:02:03.520><c> powerful</c><00:02:04.159><c> gun</c><00:02:04.560><c> and</c><00:02:04.799><c> modern</c>
00:02:05.190 --> 00:02:05.200 align:start position:0%
thanks to a powerful gun and modern
00:02:05.200 --> 00:02:06.149 align:start position:0%
thanks to a powerful gun and modern
ammunition
00:02:06.149 --> 00:02:06.159 align:start position:0%
ammunition
00:02:06.159 --> 00:02:09.830 align:start position:0%
ammunition
`
分割后这句的ASS
`Dialogue: 0,0:02:02.70,0:02:05.19,Default,,0,0,0,,thanks to a powerful gun and modern
`

这似乎是由于最后一个词缺乏word time导致的 需要的话我可以提供源文件
VTT字幕是通过youtube-dl获取的

**Comment by Sofronio** [comment]
我也发现了，我看了一下vtt文件，应该是单字独立成行被忽略了，之前youtube没有这样的问题。我抽空改一下。

**Comment by Sofronio** [comment]
fixed on v0.0.3.4
